---
- name: Install Apache2 On Debian 8 and down
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
  - apache2-mpm-event
  - php5-gd
  - php5-mysql
  - php5-curl
  - php5-mcrypt  
  - php5-fpm
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int < 9

- name: Install Apache2 On Debian 9 and up
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
  - apache2
  - php7.0-gd
  - php7.0-mysql
  - php7.0-curl
  - php7.0-mcrypt
  - php7.0-fpm
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int > 8
  
- name: add user
  user: 'uid=1000 name={{ ansible_www_user }} password={{ ansible_ftp_pass }} shell=/bin/bash home=/home/{{ ansible_www_user }} groups=adm'

- name: Push Vhost template
  template: src=apache_2.4-vhost.conf.j2 dest=/etc/apache2/sites-enabled/{{ ansible_www_domain }}.conf mode=644 owner=root group=root
  notify:
  - restart apache2
  
- name: Push FPM-pool template for php 5
  template: src=fpm-pool.conf.j2 dest=/etc/php5/fpm/pool.d/{{ ansible_www_user }}.conf mode=644 owner=root group=root
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int < 9
  notify:
  - restart php5-fpm

- name: Push FPM-pool template for php 7
  template: src=fpm-pool.conf.j2 dest=/etc/php/7.0/fpm/pool.d/{{ ansible_www_user }}.conf mode=644 owner=root group=root
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int > 8
  notify:
  - restart php7.0-fpm
  
- name: Remove default php5-fpm conf
  file: path=/etc/php5/fpm/pool.d/www.conf state=absent
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int < 9
  notify:
  - restart php5-fpm
  
- name: Remove default php7.0-fpm conf
  file: path=/etc/php/7.0/fpm/pool.d/www.conf state=absent
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int > 8
  notify:
  - restart php7.0-fpm
  
- name: Create /home/{{ ansible_www_user }}/{{ ansible_www_domain }}
  file: dest=/home/{{ ansible_www_user }}/{{ ansible_www_domain }}/ mode=755 owner={{ ansible_www_user }} group={{ ansible_www_user }} state=directory


- name: Create /home/{{ ansible_www_user }}/logs
  file: dest=/home/{{ ansible_www_user }}/logs mode=755 owner={{ ansible_www_user }} group={{ ansible_www_user }} state=directory
  
- name: add index.php
  copy: src=index.php dest=/home/{{ ansible_www_user }}/{{ ansible_www_domain }}/index.php mode=644 owner={{ ansible_www_user }} group={{ ansible_www_user }}
  
- name: enables the Apache2 modules
  action: apache2_module state=present name={{ item }}
  with_items:
  - rewrite
  - headers
  - expires
  - proxy_fcgi
  notify:
  - restart apache2

- name: remove the default Apache2 vhost on Debian 8 later
  file: path="/etc/apache2/sites-enabled/000-default.conf" state=absent
  notify:
  - restart apache2

- name: Pushes logrotate.d script
  template: src=logrote-apache2.j2 dest=/etc/logrotate.d/apache2-managed mode=0640 owner=root group=root